### ISSUE TITLE
Missing docs for subscribing command handlers.

### ISSUE THREAD

**Issue by BartoszBartniczak** [broadway/broadway-bundle#32]
I cannot find a way to automaticly register (subscribe) CommandHandlers in CommandBus. Is there a way? Should I do it by DependencyInjection or other similar way?

In demo app, there is config file named `domain.xml`, and the `broadway_demo.basket.command_handler` is tagged by `broadway.command_handler`, but in my app it doesn't work ( I created a service in `service.xml`).

You should fullfil the missing part of the docs :wink:

**Comment by szepczynski** [comment]
To subscribe handler you should create service tagged with `broadway.command_handler`. Here is one of my handlers defined as yaml service container definition:

```
services:
    # User
    user.handler.user_handler:
        class: User\Domain\Handler\UserHandler
        arguments:
          - "@user.repository.user_repository"
          - "@security.encoder_factory"
        tags:
          - { name: broadway.command_handler }
```

Are you sure is your service.xml loading by symfony?
