### ISSUE TITLE
Cannot specify custom Event Store

### ISSUE THREAD

**Issue by micheleorselli** [broadway/broadway-bundle#38]
Hi all,
I'm trying to define a custom event store implementation following the guidelines in the README: I created a class implementing Broadway\EventStore\EventStore and exposed it as a service. 

When I try to use it specifying this configuration
```yaml
broadway:
    event_store: 'AppBundle\LegacyPhroophEventStore'
```

I got an error: `Invalid type for path "broadway.event_store". Expected array, but got string`

Is there something I got wrong? Using broadway 1.1.0 with BroadwayBundle 0.2.3

**edit**: it seems then current bundle configuration does not allow this. It needs to be changed in something like 

```
broadway:
    event_store:
        repository: custom
        custom: "AppBundle\LegacyPhroophEventStore"
```

What do you think? I can send a PR for that
