### ISSUE TITLE
Can't create events table.

### ISSUE THREAD

**Issue by bruli** [broadway/broadway-bundle#40]
I'm using bundle version 0.3.0 and I can't create my table events.
I'm reading doc but I can works with this bundle. Is documentation right?.

I'm installed with composer:

 ```bash
broadway/broadway                     1.1.0   Infrastructure and testing helpers for creating CQRS...
broadway/broadway-bundle              0.3.0   Symfony bundle for broadway/broadway.
broadway/broadway-saga                0.2.1   Proof-of-concept component providing saga functional...
broadway/event-store-dbal             0.1.2   Event store implementation using doctrine/dbal
broadway/uuid-generator               0.4.0   UUID generator for broadway/broadway. matthiasnoback/broadway-serialization v2.1.0  Serialization helpers for Broadway
```
My AppKernel:

```php
public function registerBundles()
    {
        $bundles = [
           ...
            new \JMS\SerializerBundle\JMSSerializerBundle(),
            new \Broadway\Bundle\BroadwayBundle\BroadwayBundle(),
            new \BroadwaySerialization\SymfonyIntegration\BroadwaySerializationBundle()
           ....
        ];

...
        return $bundles;
    }
```

My config:

services.yml
```yml
services:
  my.event_store.dbal.connection:
    class: Broadway\EventStore\Dbal\DBALEventStore
    arguments:
      - "@doctrine.dbal.default_connection"
      - "@broadway.serializer.payload"
      - "@broadway.serializer.metadata"
      - "events"
      - false
      - "@broadway.uuid.converter"
```

config.yml

```yml
broadway:
  event_store: "my.event_store.dbal.connection"
```

When I run command:

```bash
bin/console broadway:event-store:schema:init

                                                                              
  [Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]  
  The parameter "broadway.event_store.dbal.connection" must be defined.       
                                                                              

```

**Comment by ambersariya** [comment]
Hi @bruli 

In `app/config/config.yml` you need to add the following.

```
parameters:
    broadway.event_store.dbal.connection: 'default'

...

doctrine:
    dbal:
         default_connection:   default
```

Hope that makes sense
