### ISSUE TITLE
Where are broadway event-store schema commands?

### ISSUE THREAD

**Issue by bruli** [broadway/broadway-bundle#54]
Hi.

I'm installed Broadway bundle in a symfony4 project. But I can't execute broadway commands to create event store schema.

I've got installed:
```
broadway/broadway                   2.0.1              Infrastructure and testing helpers for creating CQRS and event sourced applications.
broadway/broadway-bundle            0.4.1              Symfony bundle for broadway/broadway.
broadway/event-store-dbal           0.2.0              Event store implementation using doctrine/dbal
broadway/uuid-generator             0.4.0              UUID generator for broadway/broadway.
```
Registered bundle:

```
<?php

return [
    JMS\SerializerBundle\JMSSerializerBundle::class => ['all' => true],
    Broadway\Bundle\BroadwayBundle\BroadwayBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    ...
];
```
In config/packages/broadway.yaml
```
broadway:
  event_store: "my_dbal_event_store"
```
In config/services.ymal
```
services:
    my_dbal_event_store:
      class: Broadway\EventStore\Dbal\DBALEventStore
      arguments:
        - "@doctrine.dbal.default_connection"
        - "@broadway.serializer.payload"
        - "@broadway.serializer.metadata"
        - "events"
        - false
        - "@broadway.uuid.converter"
```
Any idea why I can see commands?.
Thks.
