### ISSUE TITLE
improve bundle configuration

### ISSUE THREAD

**Issue by othillo** [broadway/broadway-bundle#9]
requirement: using a custom implementation (event store, read model, saga) should be configurable in the bundle by specifying a service id, e.g.:

``` yaml
broadway:
    event_store:
            type: service
            id: my_acme.event_store
```

as proposed in
* https://github.com/broadway/broadway/issues/227
* https://github.com/broadway/broadway/pull/274
* https://github.com/broadway/broadway-bundle/pull/16

or

``` yaml
broadway:
    event_store: my_acme.event_store # default "broadway.event_store.in_memory"
```

see POC in https://github.com/broadway/broadway-bundle/pull/18/commits/1d89930bfbdce2f75dbd049e52960f04d6520536

another solution is to tag your custom implementation and have a compile pass register them.
